
def disco2(p1,p2,p3):
    print(p1.items)
    print(p2.items)
    print(p3.items,"\n")
    x= p1.pop()
    p2.push(x)
    print(p1.items)
    print(p2.items)
    print(p3.items,"\n")
    x=p1.pop()
    p3.push(x)
    print(p1.items)
    print(p2.items)
    print(p3.items,"\n")
    x=p2.pop()
    p3.push(x)
    print(p1.items)
    print(p2.items)
    print(p3.items,"\n")